MODEL_NAME = 'wb_dl3pmn'
# MODEL_NAME = 'wb_ulite'
OUTPUT_STRIDE = 16
NUM_CLASSES = 3
INPUT_SIZE = (512, 512)

# Training
DATASET_NAME = 'Whiteboard-Semantic-Seg'
DATASET_VERSION = 18
BATCH_SIZE = 15
TRAINING_EPOCHS = 90
