# MODEL_NAME = 'wb_dl3pmn'
MODEL_NAME = 'wb_dl3prn50'
OUTPUT_STRIDE = 16
NUM_CLASSES = 3
INPUT_SIZE = (512, 512)

# Training
DATASET_NAME = 'Whiteboard-Semantic-Seg'
DATASET_VERSION = 19
BATCH_SIZE = 48
TRAINING_EPOCHS = 90
